### ISSUE TITLE
Build basic ui with chakra

### ISSUE THREAD

**Issue by Green-Ranger11** [MLH-Fellowship/owlhub#6]
Set up chakra UI on the react application and build basic barebones prototype

**Comment by kushalShukla-web** [comment]
can i do this ?

**Comment by kushalShukla-web** [comment]
can i do this ?

**Comment by Green-Ranger11** [comment]
Hi @kushalShukla-web thanks for enquiring! 
This is a repository for our orientation hackathon with our team hence we won't be letting others be able to contribute to this.
